#!/bin/dash

repo_name='.tigger'

if test -d $repo_name
then
    echo "$0: error: .tigger already exists" 1>&2
    exit 1 
else
    mkdir "$repo_name"
    mkdir "$repo_name/index"
    mkdir "$repo_name/commits"
    echo -n > "$repo_name/TIGGER_COMMIT_LOG"

    echo "Initialized empty tigger repository in $repo_name"
    exit 0
    
fi